lwIP - Disable -Werror
The latest version of lwIP (2.0.3) provokes `unused-const-variable`
warnings in some versions of gcc.  For example:

    Error: net/ip/lwip_base/src/apps/httpd/fsdata.c:137:27: error: 'dummy_align__index_html' defined but not used [-Werror=unused-const-variable=]
     static const unsigned int dummy_align__index_html = 2;
                               ^~~~~~~~~~~~~~~~~~~~~~~

We can't disable this particular warning in the `lwip_core` package's
cflags, because older versions of gcc complain when they don't
recognize the command line option:

    cc1: error: unrecognized command line option '-Wno-unused-const-variable' [-Werror]

This commit disables all "unused" warnings in the `lwip_core` package by
adding the `-Wno-unused` cflag.