Squashed commit of the following:
commit 8a15273300433c08375c8f311a897d7ec9a12b26
Author: Gordon Chaffee <gordon@runtime.io>
Date:   Thu Feb 18 10:51:24 2016 -0800

    Fix compile error on Linux

    error: format not a string literal and no format arguments
       [-Werror=format-security]