baselibc: Fix memset compilation error on gcc15
This fixes the memset compilation error seen on gcc 15.

/tmp/cccS6DLj.s:50: Error: cannot honor width suffix -- `adds r3,ip,r2'
/tmp/cccS6DLj.s:57: Error: cannot honor width suffix -- `strb r1,[ip,r2]'
/tmp/cccS6DLj.s:61: Error: cannot honor width suffix -- `str r1,[ip,r2]'
/tmp/cccS6DLj.s:66: Error: cannot honor width suffix -- `strb r1,[ip,r2]'

caused by complier placing parameters (dst in this case) into high
registers. Since the memset implementation uses instructions that
update the CPSR, the use of high registers will cause errors as above.

This fixes this issue by forcing compiler to use low registers.
'c' aka 'val' operand constraint as not changed by function is changed
to "r" meaning it is read-only operand.