util/cbmem: Fix test case 3 compilation
Removed unused variable

repos/apache-mynewt-core/util/cbmem/selftest/src/testcases/
    cbmem_test_case_3.c:29:9: error: variable 'i' set but not
    used [-Werror,-Wunused-but-set-variable]
4941
    int i;
4942
        ^
4943
1 error generated.