sysview: Fix build for c++
Initializing non-const char pointer with constant string literal
is an error in c++ according to g++ compiler.
error: ISO C++ forbids converting a string constant to 'char*' [-Werror=write-strings]

This assignment even for c build is not useful since
asprintf assigns new value (possible NULL) to desc anyway.

This change just drops meaningless initialization that makes g++ unhappy.