encoding/tinycbor: Fix compilation with latest GCC
Those were added in C23.

In file included from repos/apache-mynewt-core/encoding/tinycbor/
    src/cborencoder_close_container_checked.c:33:
repos/apache-mynewt-core/encoding/tinycbor/include/tinycbor/
    compilersupport_p.h:160:11: error: ‘unreachable’ redefined [-Werror]
  160 | #  define unreachable() __builtin_unreachable()
      |           ^~~~~~~~~~~
In file included from repos/apache-mynewt-core/encoding/tinycbor/
    include/tinycbor/cbor.h:30,
                 from repos/apache-mynewt-core/encoding/tinycbor/
    src/cborencoder_close_container_checked.c:31:
/usr/lib/gcc/x86_64-redhat-linux/15/include/stddef.h:468:9: note: this is
     the location of the previous definition
  468 | #define unreachable() (__builtin_unreachable ())
      |         ^~~~~~~~~~~
cc1: all warnings being treated as errors