nimble/phy: Fix build error on nRF52
nRF52 does not have symbols for 125/500 data rates in CCM defined (for
LE Coded PHY - we only allow 1M on nRF52 anyway). Also CCM is only
configured if encryption is enabled.

Error: repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c: In
function 'ble_phy_get_ccm_datarate':
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:505:16:
error: 'CCM_MODE_DATARATE_125Kbps' undeclared (first use in this
function)
         return CCM_MODE_DATARATE_125Kbps << CCM_MODE_DATARATE_Pos;
                ^~~~~~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:505:16:
note: each undeclared identifier is reported only once for each function
it appears in
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:507:16:
error: 'CCM_MODE_DATARATE_500Kbps' undeclared (first use in this
function)
         return CCM_MODE_DATARATE_500Kbps << CCM_MODE_DATARATE_Pos;
                ^~~~~~~~~~~~~~~~~~~~~~~~~