openocd: Fix openocd_load for Windows
openocd expects unix style file names even on Windows.

Before pathc:
$ newt load hifive1-boot
Loading bootloader
Error:
Downloading bin\targets\hifive1-boot\app\apps\boot\boot.elf.bin to 0x20000000
GNU MCU Eclipse 64-bit Open On-Chip Debugger 0.10.0+dev-00462-gdd1d90111 (2019-01-18-11:42)
Licensed under GNU GPL v2
...
...
auto erase enabled
Error: couldn't open bin        argetshifive1-bootppppoooot.elf.bin

Windows style path was passed and \ was treated as escape \t - tab

After patch is applied flashing of hifive1 and bluepill works