nimble/ll: Fix for compiler warning
This patch solves issue which is visible when building with -Og option.
ble_ll_conn.c:2365:18: error: 'init_addr' may be used uninitialized in this function [-Werror=maybe-uninitialized]