battery: Prevent `maybe-uninitialized` warning
repos/apache-mynewt-core/kernel/os/include/os/os_time.h:109:59: error: 'next_poll' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This is a spurious warning `next_poll` is initialized before it is used.
This warning is detected in debug build only, optimized code does not
see it as a problem.
Added initialization to disable warning.