hw/util/i2cn: Remove false positive warning
gcc 7.1 when -Og is specified does not see that rc variable
is always initialized.
repos/apache-mynewt-core/hw/util/i2cn/src/i2cn.c:23:12: error: 'rc' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This adds initialization. It does not impact optimized builds
since compiler detects that assigning 0 is not needed.