crypto: mbedtls: Fix pic32mz builds
Some time ago include of <syscfg/syscfg.h> was changed
in many files to <os/mynewt.h>.

This change prevents build of mbedtls for pic32mz chips
due to name conflict:
repos/apache-mynewt-core/crypto/mbedtls/src/aes.c:418:17: error: conflicting type qualifiers for 'RCON'
 static uint32_t RCON[10];
microchip\xc32\v3.01\pic32mx\include\proc\pic32mz-ef\p32mz2048efh064.h:646:28: note: previous declaration of 'RCON' was here
 extern volatile uint32_t   RCON __attribute__((section("sfrs"), address(0xBF801240)));

This inclusion of mynewt.h is not really needed to build mbedtls library so this
reverts it back to what it used to be.