bsp/apollo3_evb: Fix blinky build
LED_BLINK_PIN was defined as MYNEWT_VAL for this board
but now syscfg val LED_BLINK_PIN has default value LED_BLINK_PIN
This causes build error:
Error: In file included from apps/blinky/src/main.c:25:
apps/blinky/src/main.c: In function 'mynewt_main':
repos/apache-mynewt-core/hw/bsp/apollo3_evb/include/bsp/bsp.h:51:25: error: implicit declaration of function 'MYNEWT_VAL' [-Wimplicit-function-declaration]
   51 | #define LED_BLINK_PIN   MYNEWT_VAL(LED_0_PIN)
      |                         ^~~~~~~~~~

To fix this expression MYNEWT_VAL(LED_0_PIN)
is changed to MYNEWT_VAL_LED_0_PIN
Additionaly changed other LEDs and BUTTONs the same manner