sys/stats: Fix build warnings when stats are stubbed
In several places return value of stats_init_and_reg() is ignored.
When stub implementation is used this evaluates to just 0 then
there are statements like:
   0;
which are reported in following way

Error: In file included from repos/apache-mynewt-core/hw/bus/include/bus/bus_driver.h:26,
                 from repos/apache-mynewt-core/hw/bus/src/bus.c:25:
repos/apache-mynewt-core/hw/bus/src/bus.c: In function 'bus_dev_init_func':
repos/apache-mynewt-core/sys/stats/stub/include/stats/stats.h:75:33: error: statement with no effect [-Werror=unused-value]
   75 | #define stats_init_and_reg(...) 0
      |                                 ^
repos/apache-mynewt-core/hw/bus/src/bus.c:250:5: note: in expansion of macro 'stats_init_and_reg'
  250 |     stats_init_and_reg(STATS_HDR(bdev->stats),

Now return value from stats_init_and_reg() is assigned to rc and verified by assert
that will fix problem with 0; statement.