nordic/i2c: Fix for compiler warning
This patch solves issue which is visible when building with -Og option.

hal_i2c.c:251:9: error: 'rc' may be used uninitialized in this function [-Werror=maybe-uninitialized]