nimble/controller: Fix build issue when PHY is not set
This patch fixes following issue:

Error:
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_sched.c: In
function 'ble_ll_sched_aux_scan':
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_sched.c:1350:9:
error: variable 'phy_mode' set but not used
[-Werror=unused-but-set-variable]