sensors: Fix tsl2561 shell build
argv[2] is a pointer but was compared to character constant. Since
argv[2] cannot point to empty string if argc == 3 simply remove this
check.

Error: repos/apache-mynewt-core/hw/drivers/sensors/tsl2561/src/tsl2561_shell.c:
    In function 'tsl2561_shell_cmd_en':
repos/apache-mynewt-core/hw/drivers/sensors/tsl2561/src/tsl2561_shell.c:351:21:
    error: comparison between pointer and zero character constant [-Werror=pointer-compare]
  351 |         if (argv[2] != '\0' && *endptr == '\0' &&
      |                     ^~
repos/apache-mynewt-core/hw/drivers/sensors/tsl2561/src/tsl2561_shell.c:351:13: note:
    did you mean to dereference the pointer?
  351 |         if (argv[2] != '\0' && *endptr == '\0' &&