hw/sensor/test: Exclude CLI code
The `util/parse` package fails to compile on some machines with this
error:

    error: implicit declaration of function 'strcasecmp'

The problem is that some systems declare `strcasecmp` in <string.h>,
while others require <strings.h> to be included.